### PR TITLE
Create a Product

### PR DESCRIPTION
**Pull request by tstrotherIV**
on the 'sell' tab you are able to create a product, add an image, and it will post to the DB.

### CODE REVIEW

**Review by kirksudduth — APPROVED** [review]
👍 
LET'S SELL SOME STUFF

**Review by sarahholder — APPROVED** [review]
🦕  Dino-mite!

**Review by LukeEsworthy — APPROVED** [review]
👍. AWESOME

**Review by kirksudduth — APPROVED** [review]
👍 👍

**Review by sarahholder — APPROVED** [review]
🦕  good catch on the integer to float.

**Pull request merged**
