### PR TITLE
Sh login

### PR DESCRIPTION
**Pull request by sarahholder**
FInished registration, auth and login.

Vierifed new user creation in database. 

Styled Navbar and buttons for login/registration/logout and shopping cart.

### CODE REVIEW

**Review by kirksudduth — APPROVED** [review]
👍

**Review by tstrotherIV — APPROVED** [review]
👍

**Review by rsnasraty — APPROVED** [review]

**Review by kirksudduth — APPROVED** [review]
APPROVED
👍

**Review by kirksudduth — APPROVED** [review]
NOT APPROVED
👎

**Pull request merged**
